DELIMITER ;

SHOW WARNINGS;

DROP TABLE IF EXISTS news_feed;

CREATE TABLE news_feed (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'NFID',
  source_feed_id INT UNSIGNED NOT NULL COMMENT 'NFSRCFEEDID',
  headline TEXT COMMENT 'NFHEADLINE',
  FOREIGN KEY (source_feed_id) REFERENCES REFDATA.news_feed_source(id)
);
